{% set version = '0.1-2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-roloc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/roloc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/roloc/roloc_{{ version }}.tar.gz
  sha256: e84e6c684e4382bd988fb389df1c48fce3e9960d18798efd1701b6cb544e42b8

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-colorspace
  run:
    - r-base
    - r-colorspace

test:
  commands:
    - $R -e "library('roloc')"           # [not win]
    - "\"%R%\" -e \"library('roloc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=roloc
  license: GPL-2.0-or-later
  summary: Functions to convert an R colour specification to a colour name. The user can select
    and create different lists of colour names and different colour metrics for the
    conversion.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: roloc
# Type: Package
# Title: Convert Colour Specification to Colour Name
# Version: 0.1-2
# Author: Paul Murrell
# Maintainer: Paul Murrell <paul@stat.auckland.ac.nz>
# Description: Functions to convert an R colour specification to a colour name. The user can select and create different lists of colour names and different colour metrics for the conversion.
# License: GPL-2 | GPL-3
# Imports: grDevices, methods, parallel, colorspace
# Suggests: grid, ggplot2, testthat
# NeedsCompilation: no
# Packaged: 2024-01-22 19:08:04 UTC; pmur002
# Repository: CRAN
# Date/Publication: 2024-01-22 20:00:08 UTC
